### ISSUE TITLE
touched() returns incorrect bool

### ISSUE THREAD

**Issue by 661020786** [solderparty/arduino_tsc2004#1]
Running on my Adafruit Feather M0, my loop() was always blocking on readData().  I believe the problem is that touched() was returning 'true' even when no touch was detected (and thus no data for readData()).

If I am reading the datasheet correctly, I believe a "touch detected" is signalled by bit15 being set in CRF0.  The current touched() code returns true whenever CRF0 is non-zero, which happens frequently even when no touch was detected.  

I believe touched() should be something like:

     return readRegister16(_REG_CFR0) & (CFR0_PENMODE | CFR0_STATUS) >>15;

I was able to workaround the problem in my test code, by adding a TOUCHED_DETECTED macro that tests bit15 only

     #define _REG_CFR0       (0xC << 3)
     #define CFR0_STATUS             (1 << 14)
     #define CFR0_PENMODE            (1 << 15)
     #define TOUCH_DETECTED(t)   (bool) (((t).readRegister16(_REG_CFR0) & (CFR0_PENMODE | CFR0_STATUS) ) >> 15)

**Comment by buismaarten** [comment]
I had the same problem yesterday, you could probably solve this with:

```
return (readRegister16(_REG_CFR0) & CFR0_PENMODE) != 0;
```

**Comment by arturo182** [comment]
Oh, this issue totally skipped my mind, I'm so sorry. I will work on this and fix it soon.

**Comment by SapientHetero** [comment]
Same issue here. Fixed by replacing

return readRegister16(_REG_CFR0) & (CFR0_PENMODE | CFR0_STATUS);

with 

return readRegister16(_REG_CFR0) & CFR0_PENMODE;

because CFR0_STATUS tells us whether A/D is busy; only CFR0_PENMODE (bit 15) indicates whether touch has occurred.
